h2 =          { scaopac = 0.673e-27, mmw = 2.33 }
h2he =        { scaopac = 0,         mmw = 2.55 } # 87% H2, 13% He
he =          { scaopac = 0,         mmw = 4.00 }
h- =          { scaopac = 0,         mmw = 1.01 }
h2o =         { scaopac = 2.454e-27, mmw = 18.02 }
ch4 =         { scaopac = 6.50e-27,  mmw = 16.04 }
12co =        { scaopac = 4.14e-27,  mmw = 28.01 }
13co =        { scaopac = 4.14e-27,  mmw = 29.00 }
co =          { scaopac = 4.14e-27,  mmw = 28.01 }
co2 =         { scaopac = 6.82e-27,  mmw = 44.01 }
nh3 =         { scaopac = 4.80e-27,  mmw = 17.03 }
h2s =         { scaopac = 0,         mmw = 34.07 }
Burrows_alk = { scaopac = 718.9e-27, mmw = 23.94 }
Lupu_alk =    { scaopac = 718.9e-27, mmw = 23.94 }
crh =         { scaopac = 84.0e-27,  mmw = 53.00 }
feh =         { scaopac = 84.0e-27,  mmw = 56.85 }
tio =         { scaopac = 183.3e-27, mmw = 63.87 }
vo =          { scaopac = 131.3e-27, mmw = 66.94 }
hcn =         { scaopac = 0,         mmw = 27.03 } # todo on scattering cross section
n2 =          { scaopac = 0,         mmw = 28.01 } # todo on scattering cross section
ph3 =         { scaopac = 0,         mmw = 34.00 } # todo on scattering cross section